### ISSUE TITLE
Exception by wrong import statement is not visible to caller

### ISSUE THREAD

**Issue by hartmut27** [antlr/stringtemplate4#120]
ST4.0.8 is quite mature. Most errors in the group files are promoted to to caller. 

But in the described case here, the caller cannot determine, if a error occured, since the exception is catched and not promoted.

Given a group file `BmjBra.stg`:

    import "Uploader.stg"   
    import "FormularBra.stg"
    import "DOES_NOT_EXIST_DOES_NOT_EXIST.stg"

When ST4 is called e.g. by

    ST g = stGroup().getInstanceOf("someTemplate123");

This leads to

    can't load group file file:/C:/Users/hape/bm/bmj/src/de/hape/bmj/templates/BmjBra.stg
    Caused by: java.lang.IllegalArgumentException: No such group file:     DOES_NOT_EXIST_DOES_NOT_EXIST.stg
    	at org.stringtemplate.v4.STGroupFile.<init>(STGroupFile.java:69)
    	at org.stringtemplate.v4.STGroup.importTemplates(STGroup.java:563)
    	at org.stringtemplate.v4.compiler.GroupParser.group(GroupParser.java:199)
    	at org.stringtemplate.v4.STGroup.loadGroupFile(STGroup.java:612)
    	at org.stringtemplate.v4.STGroupFile.load(STGroupFile.java:139)
    	at org.stringtemplate.v4.STGroupFile.load(STGroupFile.java:128)
    	at org.stringtemplate.v4.STGroup.lookupTemplate(STGroup.java:230)
    	at org.stringtemplate.v4.STGroup.getInstanceOf(STGroup.java:165)
    	at de.hape.bmj.core.BmTemplateMgr$BmSTGroup.stByName(BmTemplateMgr.java:56)

The error log in the console (shown above) is __absolutely correct__, but 

    ST g = stGroup().getInstanceOf("someTemplate123");

cannot be surrounded by a try ... catch ... block, since the RuntimeException is handeled inside and not promoted to outside. That means the respective thread is terminated by the RuntimeException, but the ST4 library user is not able to identify/intercept those problems programmatically.

**Comment by ericvergnaud** [comment]
Can you not catch Throwable?

**Comment by hartmut27** [comment]
The Exception in question is of kind RuntimeException (which is an
extension of class Exception), no need for Throwable.

2015-08-02 22:58 GMT+02:00 ericvergnaud <notifications@github.com>:

> Can you not catch Throwable?
>

**Comment by hartmut27** [comment]
I've rechecked this now, but as expected, catching Throwable does not solve the issue unfort.

**Comment by sharwell** [comment]
The problem is exceptions thrown by [this call to `group`](https://github.com/antlr/stringtemplate4/blob/ce9f65b755b2779b7f018e3e46f50f03b04dc3f6/src/org/stringtemplate/v4/STGroup.java#L612) are swallowed by the exception handler in the same method. You may be able to handle this situation my setting `STGroup.errMgr` to your own instance of `ErrorManager`.

```java
STGroup group = ...;                       // your existing group
STErrorListener listener = ...;            // your custom error handling logic
group.errMgr = new ErrorManager(listener);
```

**Comment by parrt** [comment]
@hartmut27 Did setting a STErrorListener work for you?

**Comment by hartmut27** [comment]
@parrt Yes, ```STErrorListener``` fits very well.
Thank You!

e.g. ```myStGroup.errMgr = new ErrorManager(new STErrorListener() { ... } ```

**Comment by parrt** [comment]
ok, thanks
