### ISSUE TITLE
Unable to use square brackets as delimiters

### ISSUE THREAD

**Issue by Jericho** [antlr/stringtemplate4#183]
Using StringTemplate4 nuget package version 4.0.8 in Visual Studio 2015. 

The following C# code:
```
var st = new Template("Dear [firstname]", '[', ']');
st.Add("firstname", "Bob");
var result = st.Render();
```
Yields the following exception: `Exception of type 'Antlr4.StringTemplate.Compiler.TemplateException' was thrown.` with the following stack trace:

```
at Antlr4.StringTemplate.Compiler.TemplateCompiler.ReportMessageAndThrowTemplateException(ITokenStream tokens, IToken templateToken, Parser parser, RecognitionException re)
at Antlr4.StringTemplate.Compiler.TemplateCompiler.Compile(String srcName, String name, List`1 args, String template, IToken templateToken)
at Antlr4.StringTemplate.Template..ctor(TemplateGroup group, String template)
```

I had a discussion with Sam Harwell in the `antlrcs` gitter room and he pointed out that the issue is with the closing square bracket.

**Comment by ncharles** [comment]
This looks a lot like https://github.com/antlr/stringtemplate4/issues/172

**Comment by parrt** [comment]
We added a warning for those delimiters. https://github.com/antlr/stringtemplate4/pull/149
