### ISSUE TITLE
Why the project depends on antlr runtime 3.5.2?

### ISSUE THREAD

**Issue by guwenqing** [antlr/stringtemplate4#262]
The pom file still depend the ST project on antlr runtime 3.5.2, and it is not compatible to antlr4-runtime 4.7.2.
Will you migrate the ST project over there?

When using
https://mvnrepository.com/artifact/org.antlr/antlr4-runtime/4.7.2

java.lang.NoClassDefFoundError: org/antlr/runtime/CharStream
	at org.fc.mdt.core.karma.write.node.KarmaMetaProperty.render(KarmaMetaProperty.java:95)
	at org.fc.mdt.core.karma.write.segment.KarmaMetaModeWrite.visitProperty(KarmaMetaModeWrite.java:80)
	at org.fc.mdt.core.karma.write.tests.KarmaASTMetaPropertyTest.writeShouldGetCorrectKarmaFromObject(KarmaASTMetaPropertyTest.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.lang.ClassNotFoundException: org.antlr.runtime.CharStream
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 30 more

**Comment by parrt** [comment]
Howdy. It is written in the previous version so I can't upgrade. The packages should be different so I'm not sure why there would be a conflict with v4.

**Comment by parrt** [comment]
by the way `java.lang.NoClassDefFoundError: org/antlr/runtime/CharStream` indicates that v4 and ST are written in v3 so you will have to include that as well in your maven requirements.

**Comment by KvanTTT** [comment]
By the way, ANTLR 4 is also based on ANTLR 3.
