### ISSUE TITLE
NPE in STGroup.loadTemplateFile()

### ISSUE THREAD

**Issue by kamstrup** [antlr/stringtemplate4#49]
With ST 4.0.7 calling `STGroup.getInstanceOf()` on a `STRawGroupDir` or `STGroupDir` always results in a `NullPointerException`.

The `impl` variable declared in `STGroup` line 662 is always null and accessing it in line 663 causes the NPE. This is indeed on first invocation, so the `STGroup.templates` cache has never been supplied with a `CompiledST` instance.

Stack trace if it matters:

```
Exception in thread "pool-2-thread-1" java.lang.NullPointerException
    at org.stringtemplate.v4.STGroup.loadTemplateFile(STGroup.java:663)
    at org.stringtemplate.v4.STGroupDir.loadTemplateFile(STGroupDir.java:176)
    at org.stringtemplate.v4.STGroupDir.load(STGroupDir.java:136)
    at org.stringtemplate.v4.STGroup.lookupTemplate(STGroup.java:237)
    at org.stringtemplate.v4.STGroup.getInstanceOf(STGroup.java:172)
    at com.bioql.web.render.RenderingService.render(RenderingService.java:43)
    at com.bioql.web.handlers.HelloWorldTemplateHandler.handle(HelloWorldTemplateHandler.java:29)
    at com.bioql.web.HttpServer$DefaultContainer$1.run(HttpServer.java:60)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)
```

**Comment by arenaux** [comment]
Hi,

I have the same issue as well (with STRawGroupDir and STGroupDir), with this bit:
```
STRawGroupDir dir = new STRawGroupDir(TEMPLATE_DIR);
ST st = dir.getInstanceOf(name);
```
Here, the dir variable is null.

When I debugged, I found out that it is a problem with the root (URL) variable used in STRawGroupDir, which is constructed by adding an extra slash at the end, when using the default constructor.
But in my case, that extra slash is unnecessary because there is already one at the end (maybe because the templates are loaded from another jar). That leads to have two slashes instead of just one.

The workaround I have found to prevent this is to use the constructor which defines the root (ll. 31, in STRawGroupDir).
```
URL wrong = Thread.currentThread().getContextClassLoader().getResource(TEMPLATE_DIR);
URL correct = new URL(wrong.toString().replaceAll("/$", ""));

STRawGroupDir dir = new STRawGroupDir(correct, null, '<', '>');

ST st = dir.getInstanceOf(name);
```

And in that case, it is working fine (in both case, because if the extra slash doesn't exist, the URL is not rewritten).

Maybe you can find a proper solution for this?

Thank you!
