### ISSUE TITLE
AutoIndentWriter null pointer exception

### ISSUE THREAD

**Issue by brandondahler** [antlr/stringtemplate4#97]
Originating from C# library, but I assume that this issue applies to the java version as well.

When processing a template that accesses an attribute returns is a null string, an exception is logged to the console:

```
context [anonymous] 1:0 internal error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Antlr4.StringTemplate.AutoIndentWriter.Write(String value) in c:\dev\stringtemplate_main\antlrcs\main\Antlr4.StringTemplate\AutoIndentWriter.cs:line 179
   at Antlr4.StringTemplate.Interpreter.WritePlainObject(ITemplateWriter out, TemplateFrame frame, Object o, String[] options) in c:\dev\stringtemplate_main\antlrcs\main\Antlr4.StringTemplate\Interpreter.cs:line 905
   at Antlr4.StringTemplate.Interpreter.WriteObject(ITemplateWriter out, TemplateFrame frame, Object o, String[] options) in c:\dev\stringtemplate_main\antlrcs\main\Antlr4.StringTemplate\Interpreter.cs:line 836
   at Antlr4.StringTemplate.Interpreter.WriteObjectNoOptions(ITemplateWriter out, TemplateFrame frame, Object o) in c:\dev\stringtemplate_main\antlrcs\main\Antlr4.StringTemplate\Interpreter.cs:line 740
   at Antlr4.StringTemplate.Interpreter.ExecuteImpl(ITemplateWriter out, TemplateFrame frame) in c:\dev\stringtemplate_main\antlrcs\main\Antlr4.StringTemplate\Interpreter.cs:line 328
   at Antlr4.StringTemplate.Interpreter.Execute(ITemplateWriter out, TemplateFrame frame) in c:\dev\stringtemplate_main\antlrcs\main\Antlr4.StringTemplate\Interpreter.cs:line 163
   at Antlr4.StringTemplate.AutoIndentWriter.Write(String value) in c:\dev\stringtemplate_main\antlrcs\main\Antlr4.StringTemplate\AutoIndentWriter.cs:line 179
   at Antlr4.StringTemplate.Interpreter.WritePlainObject(ITemplateWriter out, TemplateFrame frame, Object o, String[] options) in c:\dev\stringtemplate_main\antlrcs\main\Antlr4.StringTemplate\Interpreter.cs:line 905
   at Antlr4.StringTemplate.Interpreter.WriteObject(ITemplateWriter out, TemplateFrame frame, Object o, String[] options) in c:\dev\stringtemplate_main\antlrcs\main\Antlr4.StringTemplate\Interpreter.cs:line 836
   at Antlr4.StringTemplate.Interpreter.WriteObjectNoOptions(ITemplateWriter out, TemplateFrame frame, Object o) in c:\dev\stringtemplate_main\antlrcs\main\Antlr4.StringTemplate\Interpreter.cs:line 740
   at Antlr4.StringTemplate.Interpreter.ExecuteImpl(ITemplateWriter out, TemplateFrame frame) in c:\dev\stringtemplate_main\antlrcs\main\Antlr4.StringTemplate\Interpreter.cs:line 328
   at Antlr4.StringTemplate.Interpreter.Execute(ITemplateWriter out, TemplateFrame frame) in c:\dev\stringtemplate_main\antlrcs\main\Antlr4.StringTemplate\Interpreter.cs:line 163
```

Likely issue:

In AutoIndentWriter.java:
public int write(String str) throws IOException { ... } does not check if str is null before accessing str.length .

I can provide more details reproduction steps if needed.

**Comment by sharwell** [comment]
@brandondahler Looking at the code for the C# port, it seems the described sequence can only occur if one of the following occurs:

* `IAttributeRenderer.ToString` returns null
* `Object.ToString` returns null for some object

However, neither of these two things is allowed to occur. It appears that your application has a bug where an object provides an invalid implementation of a `ToString` method; correcting that bug would eliminate the exception when using the object.
